"""Add Product model

Revision ID: c23fc23cc720
Revises: 52a7f2ffc8ca
Create Date: 2024-07-18 11:06:11.188175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23fc23cc720'
down_revision: Union[str, None] = '52a7f2ffc8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=False),
                    # Тут добавили ручками и дальше добавляем через КС командой alembic revision --autogenerate -m "описание как хотим [OPTIONAL]"
                    sa.Column('description', sa.Text(), nullable=False),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showcase')
    # ### end Alembic commands ###
