"""добавление столбца в description таблицу Product

Revision ID: 190347f1a978
Revises: d179d8db4f58
Create Date: 2024-07-18 11:12:19.773566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190347f1a978'
down_revision: Union[str, None] = 'd179d8db4f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
